services:
  api:
    #busca os dados da api dentro da pasta backend.
    build:
      context: ./backend
      dockerfile: dockerfile

    #pega a porta 8000 dentro do container e expoe na porta 8000 do computador.
    ports:
      - "8000:8000"
    #pega as variaveis de ambiente do arquivo .env.
    env_file:
      - .env
    #garante que o serviço de api so inicie depois do redis e do db está pronto.
    depends_on:
      - redis
      - db

  frontend:
    build: ./frontend-juju
    ports: 
      - "80:80"
    depends_on:
      - api
 
  redis:
    image: redis:7
    ports:
      - "6379:6379"

  db:
    image: postgres:15 #Pega a imagem do postgres na versão 15.
    restart: always #sempre que o container parar, ele irá reiniciar.

    environment: #Variaveis de ambiente para configurar o banco de dados.
      POSTGRES_USER: juju
      POSTGRES_PASSWORD: password
      POSTGRES_DB: juju

    volumes: #Cria um volume para persistir os dados do banco de dados.
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432" #Expondo a porta 5432 do container para a porta 5432 do host.

volumes:
  postgres_data: #Nome do volume para o banco de dados.